# File generated from our OpenAPI spec
defmodule Stripe.Resources.Bancontact do
  @moduledoc """
  setup_attempt_payment_method_details_bancontact
  """

  @typedoc """
  * `bank_code` - Bank code of bank associated with the bank account. Max length: 5000. Nullable.
  * `bank_name` - Name of the bank associated with the bank account. Max length: 5000. Nullable.
  * `bic` - Bank Identifier Code of the bank associated with the bank account. Max length: 5000. Nullable.
  * `generated_sepa_debit` - The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt. Nullable. Expandable.
  * `generated_sepa_debit_mandate` - The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt. Nullable. Expandable.
  * `iban_last4` - Last four characters of the IBAN. Max length: 5000. Nullable.
  * `preferred_language` - Preferred language of the Bancontact authorization page that the customer is redirected to.
  Can be one of `en`, `de`, `fr`, or `nl` Possible values: `de`, `en`, `fr`, `nl`. Nullable.
  * `verified_name` - Owner's verified full name. Values are verified or provided by Bancontact directly
  (if supported) at the time of authorization or settlement. They cannot be set or mutated. Max length: 5000. Nullable.
  """
  @type t :: %__MODULE__{}

  defstruct [
    :bank_code,
    :bank_name,
    :bic,
    :generated_sepa_debit,
    :generated_sepa_debit_mandate,
    :iban_last4,
    :preferred_language,
    :verified_name
  ]

  @object_name "setup_attempt_payment_method_details_bancontact"
  def object_name, do: @object_name

  def expandable_fields, do: ["generated_sepa_debit", "generated_sepa_debit_mandate"]
end
